//! Windows platform backend using native Low-Level Keyboard Hooks (WH_KEYBOARD_LL).

use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use crate::core::event::{Key, KeyAction, KeyEvent, Modifiers};
use crate::core::state::EngineAction;
use crate::core::KeylautEngine;

#[cfg(target_os = "windows")]
use windows_sys::Win32::Foundation::{HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
#[cfg(target_os = "windows")]
use windows_sys::Win32::UI::Input::KeyboardAndMouse::{
    GetKeyState, SendInput, INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYEVENTF_KEYUP,
    KEYEVENTF_UNICODE, VK_BACK, VK_CONTROL, VK_DELETE, VK_DOWN, VK_END, VK_ESCAPE, VK_HOME,
    VK_LEFT, VK_LWIN, VK_MENU, VK_NEXT, VK_PRIOR, VK_RETURN, VK_RIGHT, VK_RWIN, VK_SHIFT, VK_SPACE,
    VK_TAB, VK_UP,
};
#[cfg(target_os = "windows")]
use windows_sys::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, DispatchMessageW, GetMessageW, SetWindowsHookExW, TranslateMessage,
    UnhookWindowsHookEx, HHOOK, KBDLLHOOKSTRUCT, MSG, WH_KEYBOARD_LL, WM_KEYDOWN, WM_SYSKEYDOWN,
};

#[cfg(target_os = "windows")]
const LLKHF_INJECTED: u32 = 0x00000010;

#[cfg(target_os = "windows")]
static ENGINE_HOLDER: Mutex<Option<KeylautEngine>> = Mutex::new(None);
#[cfg(target_os = "windows")]
static HOOK_HANDLE: Mutex<Option<isize>> = Mutex::new(None);
#[cfg(target_os = "windows")]
static THREAD_ID: Mutex<Option<u32>> = Mutex::new(None);

pub fn check_permissions() -> Result<(), String> {
    // Windows low-level keyboard hooks do not require special elevated permissions for standard user input.
    Ok(())
}

#[cfg(target_os = "windows")]
pub fn run(engine: KeylautEngine) -> Result<(), String> {
    {
        let mut guard = ENGINE_HOLDER.lock().unwrap();
        *guard = Some(engine);
    }

    unsafe {
        let hook = SetWindowsHookExW(
            WH_KEYBOARD_LL,
            Some(low_level_keyboard_proc),
            std::ptr::null_mut() as HINSTANCE,
            0,
        );

        if hook.is_null() {
            return Err("Failed to install Windows WH_KEYBOARD_LL hook.".to_string());
        }

        {
            let mut hook_guard = HOOK_HANDLE.lock().unwrap();
            *hook_guard = Some(hook as isize);
            let mut tid_guard = THREAD_ID.lock().unwrap();
            *tid_guard = Some(windows_sys::Win32::System::Threading::GetCurrentThreadId());
        }

        log::info!("Keylaut Windows platform backend active.");

        let mut msg: MSG = std::mem::zeroed();
        while GetMessageW(&mut msg, 0 as HWND, 0, 0) > 0 {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }

        // Cleanup
        let hook = {
            let mut guard = HOOK_HANDLE.lock().unwrap();
            guard.take()
        };
        if let Some(h) = hook {
            UnhookWindowsHookEx(h as HHOOK);
        }
    }

    Ok(())
}

#[cfg(not(target_os = "windows"))]
pub fn run(_engine: KeylautEngine) -> Result<(), String> {
    Err("Windows backend is only available when compiling for Windows.".to_string())
}

pub fn stop() {
    #[cfg(target_os = "windows")]
    unsafe {
        if let Some(tid) = *THREAD_ID.lock().unwrap() {
            windows_sys::Win32::UI::WindowsAndMessaging::PostThreadMessageW(
                tid,
                windows_sys::Win32::UI::WindowsAndMessaging::WM_QUIT,
                0,
                0,
            );
        }
    }
}

#[cfg(target_os = "windows")]
unsafe extern "system" fn low_level_keyboard_proc(
    n_code: i32,
    w_param: WPARAM,
    l_param: LPARAM,
) -> LRESULT {
    if n_code < 0 {
        return CallNextHookEx(std::ptr::null_mut(), n_code, w_param, l_param);
    }

    let kbd = *(l_param as *const KBDLLHOOKSTRUCT);

    // Ignore injected events generated by Keylaut
    if (kbd.flags & LLKHF_INJECTED) != 0 {
        return CallNextHookEx(std::ptr::null_mut(), n_code, w_param, l_param);
    }

    let is_key_down = w_param as u32 == WM_KEYDOWN || w_param as u32 == WM_SYSKEYDOWN;
    if !is_key_down {
        return CallNextHookEx(std::ptr::null_mut(), n_code, w_param, l_param);
    }

    let shift = (GetKeyState(VK_SHIFT as i32) as u16 & 0x8000) != 0;
    let ctrl = (GetKeyState(VK_CONTROL as i32) as u16 & 0x8000) != 0;
    let alt = (GetKeyState(VK_MENU as i32) as u16 & 0x8000) != 0;
    let win = (GetKeyState(VK_LWIN as i32) as u16 & 0x8000) != 0
        || (GetKeyState(VK_RWIN as i32) as u16 & 0x8000) != 0;

    let modifiers = Modifiers {
        shift,
        ctrl,
        alt,
        meta: win,
    };

    let vk = kbd.vkCode as u16;
    let key = match vk {
        VK_BACK => Key::Backspace,
        VK_RETURN => Key::Enter,
        VK_TAB => Key::Tab,
        VK_SPACE => Key::Space,
        VK_ESCAPE => Key::Escape,
        VK_LEFT => Key::Left,
        VK_RIGHT => Key::Right,
        VK_UP => Key::Up,
        VK_DOWN => Key::Down,
        VK_HOME => Key::Home,
        VK_END => Key::End,
        VK_PRIOR => Key::PageUp,
        VK_NEXT => Key::PageDown,
        VK_DELETE => Key::Delete,
        0x41..=0x5A => {
            // A-Z key
            let ch = (vk as u8) as char;
            if shift {
                Key::Char(ch)
            } else {
                Key::Char(ch.to_ascii_lowercase())
            }
        }
        _ => {
            // Attempt to translate VK to Unicode character
            let mut keyboard_state = [0u8; 256];
            windows_sys::Win32::UI::Input::KeyboardAndMouse::GetKeyboardState(
                keyboard_state.as_mut_ptr(),
            );
            let mut buf = [0u16; 4];
            let res = windows_sys::Win32::UI::Input::KeyboardAndMouse::ToUnicode(
                vk as u32,
                kbd.scanCode,
                keyboard_state.as_ptr(),
                buf.as_mut_ptr(),
                buf.len() as i32,
                0,
            );
            if res > 0 {
                if let Some(ch) = char::decode_utf16(buf[..res as usize].iter().copied())
                    .next()
                    .and_then(|r| r.ok())
                {
                    Key::Char(ch)
                } else {
                    Key::Other
                }
            } else {
                Key::Other
            }
        }
    };

    let key_event = KeyEvent {
        key,
        modifiers,
        action: KeyAction::Press,
    };

    let action = {
        let mut guard = ENGINE_HOLDER.lock().unwrap();
        if let Some(engine) = guard.as_mut() {
            engine.process_event(key_event)
        } else {
            EngineAction::Pass
        }
    };

    match action {
        EngineAction::Pass => CallNextHookEx(std::ptr::null_mut(), n_code, w_param, l_param),
        EngineAction::Suppress => 1,
        EngineAction::Replace { backspaces, text } => {
            let mut inputs: Vec<INPUT> = Vec::new();

            // Generate Backspaces
            for _ in 0..backspaces {
                inputs.push(make_key_input(VK_BACK, false));
                inputs.push(make_key_input(VK_BACK, true));
            }

            // Generate replacement Unicode characters
            for utf16_char in text.encode_utf16() {
                inputs.push(make_unicode_input(utf16_char, false));
                inputs.push(make_unicode_input(utf16_char, true));
            }

            if !inputs.is_empty() {
                SendInput(
                    inputs.len() as u32,
                    inputs.as_mut_ptr(),
                    std::mem::size_of::<INPUT>() as i32,
                );
            }

            // Suppress original trigger event
            1
        }
    }
}

#[cfg(target_os = "windows")]
unsafe fn make_key_input(vk: u16, key_up: bool) -> INPUT {
    let mut flags = 0;
    if key_up {
        flags |= KEYEVENTF_KEYUP;
    }

    INPUT {
        r#type: INPUT_KEYBOARD,
        Anonymous: INPUT_0 {
            ki: KEYBDINPUT {
                wVk: vk,
                wScan: 0,
                dwFlags: flags,
                time: 0,
                dwExtraInfo: 0,
            },
        },
    }
}

#[cfg(target_os = "windows")]
unsafe fn make_unicode_input(utf16: u16, key_up: bool) -> INPUT {
    let mut flags = KEYEVENTF_UNICODE;
    if key_up {
        flags |= KEYEVENTF_KEYUP;
    }

    INPUT {
        r#type: INPUT_KEYBOARD,
        Anonymous: INPUT_0 {
            ki: KEYBDINPUT {
                wVk: 0,
                wScan: utf16,
                dwFlags: flags,
                time: 0,
                dwExtraInfo: 0,
            },
        },
    }
}

// ---------------------------------------------------------------------------
// Windows Autostart via Startup Shortcut / Folder
// ---------------------------------------------------------------------------

fn startup_shortcut_path() -> Result<PathBuf, std::io::Error> {
    let app_data = dirs::data_dir().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::NotFound,
            "Could not determine APPDATA directory",
        )
    })?;
    Ok(app_data
        .join("Microsoft")
        .join("Windows")
        .join("Start Menu")
        .join("Programs")
        .join("Startup")
        .join("Keylaut.cmd"))
}

pub fn autostart_enable() -> Result<(), std::io::Error> {
    let shortcut_path = startup_shortcut_path()?;
    if let Some(parent) = shortcut_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let current_exe = std::env::current_exe()?;
    let cmd_content = format!("@start \"\" \"{}\" run\n", current_exe.to_string_lossy());
    fs::write(&shortcut_path, cmd_content)?;
    Ok(())
}

pub fn autostart_disable() -> Result<(), std::io::Error> {
    let shortcut_path = startup_shortcut_path()?;
    if shortcut_path.exists() {
        fs::remove_file(&shortcut_path)?;
    }
    Ok(())
}

pub fn autostart_status() -> Result<bool, std::io::Error> {
    let shortcut_path = startup_shortcut_path()?;
    Ok(shortcut_path.exists())
}

/// Checks if a background Keylaut process is running on Windows.
pub fn running_pid() -> Option<u32> {
    None
}

/// Stops a running Keylaut process on Windows.
pub fn stop_pid(_pid: u32) {}
